### ISSUE TITLE
Old segfault issue is back

### ISSUE THREAD

**Issue by drcongo** [Docker-Hub-frolvlad/docker-alpine-python3#9]
Hello (and thanks for this docker image!)

We have a django-base image which builds on yours - today I did a new build of it and I get a segfault when running the Django dev server with auto reload on. I've been digging through a bunch of issues across Github on this, and noticed you in [this thread](https://github.com/docker-library/python/issues/211). I noticed at the bottom of that thread there's someone mentioning that he segfault is back for them in Alpine 3.8. There's a thread about it specific to the django dev server [here](https://github.com/wemake-services/wemake-django-template/issues/42) too.

For now, the `threading.stack_size(2*1024*1024)` workaround is working for me but I thought you might like to know that the issue seems to be back.

**Comment by frol** [comment]
@drcongo Thanks for the heads up! I have tried to reproduce the issue, but it does not seem to show up on my end. Just a wild idea, see if your base Docker image is up-to-date (`docker pull ...`).

I suggest you also try using the https://github.com/docker-library/python image. Also, it would be great if you can provide more information about your environment (host OS, Docker version, etc) and a link to the project you build (if it is open source) or create a minimal reproducible example out of your project, otherwise, I don't have any ideas on how to catch the error.

**Comment by drcongo** [comment]
Thanks @frol, I'll try and create a minimal version that reproduces it - there is definitely a possibility that it's down to something else we're doing in there (like installing pyenv to support multiple python versions).
For the record for now, host os is macOS 10.14.1, Docker 18.09.0 (Version 2.0.0.0-mac81 29211). 

I'll report back if I can get a minimal reproducible build or work out where else the issue might lie.

**Comment by WinKingFace** [comment]
dockerfile 没有更新  3.6的

**Comment by soderluk** [comment]
I have a bottle API project going on, and suddenly we're getting segfaults on this docker image when running the server with `uwsgi`.

Locally it works perfect, by just running the API with `python application.py` but as soon as we use `uwsgi` and the first requests comes in, it segfaults. 

We pinpointed the error, and it started when we added `cryptography`, `pyjwt` and `pycrypto` to the project. We think it might have something to do with having the `cffi` library included, but debugging this issue is really hard.

We have a setup of a bottle API running inside Docker on a minikube cluster with a `invoke`-task that runs the server.
The host I'm on is Ubuntu 18.04, Docker 18.06.1-ce, minikube v0.30.0.

**Comment by frol** [comment]
@soderluk I am sorry to hear that, but I have no idea how to help you. I cannot reproduce the issue on my end, and there is nothing special about this particular image, as I just package up the upstream Alpine Linux `python3` package. I can only suggest you try [`python:3-alpine3.8`](https://hub.docker.com/_/python/) image

**Comment by soderluk** [comment]
@frol: I understand that. I just wanted to point this out, if there's anyone else with the same kind of issues :) 
I'm going to try out the python-image next.
At the moment it might be anything from musl to uwsgi that fails the whole thing...

**Comment by cridenour** [comment]
Just wanted to note I ran across segfaults with`python3.6:alpine-3.8` but it was solved with `python3.6:alpine-3.9`, using `uwsgi==2.0.17.1`

**Comment by soderluk** [comment]
@cridenour: Thanks very much for this comment! I got things working again :) million thanks!

**Comment by frol** [comment]
BTW, `frolvlad/alpine-python3` image is also based on Alpine 3.9 now.
